SELECT  *  FROM GELISLER
SELECT * FROM KIMLIK 
SELECT * FROM PARA
SELECT * FROM DOKTOR

SELECT G.DOSYANO , G.GELISNO, K.AD , K.SOYAD , G.KURUM, D.DOKTOR, Y = SUM(P.TUTAR)   --P.ACIKLAMA
FROM PARA P 
	INNER JOIN  GELISLER G   ON G.DOSYANO = P.DOSYANO AND G.GELISNO = P.GELISNO
	INNER JOIN KIMLIK K  ON G.DOSYANO = K.DOSYANO
	INNER JOIN DOKTOR D ON G.DOKTORKOD=D.DOKTORKOD
WHERE 
	G.GIRISTARIH >='2022-05-11' AND G.GIRISTARIH <='2022-05-11 23:59'
	AND K.DOSYANO='GX0000106' AND G.GELISNO=2
GROUP BY G.DOSYANO , G.GELISNO, K.AD , K.SOYAD , G.KURUM, D.DOKTOR
--ORDER BY P.SIRANO



SELECT G.DOSYANO , G.GELISNO, K.AD , K.SOYAD , G.KURUM, G.DOKTOR, TOPLAM = sum(T.TAHSIL) --T.TUR,  --T.ACIKLAMA 
FROM TAHSILAT T 
	INNER JOIN  GELISLER G   ON G.DOSYANO = T.DOSYANO AND G.GELISNO = T.GELISNO
	INNER JOIN KIMLIK K  ON G.DOSYANO = K.DOSYANO
WHERE 
	G.GIRISTARIH >='2022-05-11' AND G.GIRISTARIH <='2022-05-11 23:59'
	AND K.DOSYANO='GX0000106' AND G.GELISNO=2
	GROUP BY  G.DOSYANO , G.GELISNO, K.AD , K.SOYAD , G.KURUM, G.DOKTOR
--ORDER BY T.SIRANO



SELECT G.DOSYANO , G.GELISNO, K.AD , K.SOYAD , G.KURUM, D.DOKTOR, GELISDOKTORKOD=G.DOKTORKOD,P.DR,P.DR2 ,  P.ACIKLAMA, YAPANDR = D1.DOKTOR 
FROM PARA P 
	INNER JOIN  GELISLER G   ON G.DOSYANO = P.DOSYANO AND G.GELISNO = P.GELISNO
	INNER JOIN KIMLIK K  ON G.DOSYANO = K.DOSYANO
	left JOIN Doktor D1 ON D1.DOKTORKOD = P.DR2
	LEFT JOIN DOKTOR D ON G.DOKTORKOD=D.DOKTORKOD
WHERE 
	G.GIRISTARIH >='2022-05-11' AND G.GIRISTARIH <='2022-05-11 23:59'
	AND K.DOSYANO='GX0000106' AND G.GELISNO=2
ORDER BY P.SIRANO




