   --Ýzlem Bilgisi Yok Dönüþüm kontrollü
--Belge türü 119 ve dönüþüm var mý 0 ise sorgudaki delete i çalýþtýrýnýz.

SELECT 
       CASE WHEN EXISTS(SELECT F.YERID FROM FATURA FX WHERE FX.YERID = F.ID AND FX.YERI = 416) THEN 1 ELSE 0 END AS DONUSUM_VARMI,
                   'DELETE FROM FATURA WHERE ID ='+CONVERT(VARCHAR(10),F.ID) AS SORGU,
                   FB.ID,F.ID,FB.TUR,R.FIRMA,FB.FATURATARIH,FB.FATURANO,F.URUNID,F.ADET, 0 AS ADET,S.KOD
FROM 
       FATURA F INNER JOIN FATBASLIK FB ON FB.ID = F.FATBASID
                   INNER JOIN REHBER R ON R.ID = FB.REHBERID
                           INNER JOIN STOKLAR S ON S.ID = F.URUNID
WHERE 
       F.IZLEME IN (1,2,5) -- STOK IZLEM TURU 2 VE 5 OLAN ÝSTENRÝSE DÝÐER TÜRLERÝ EKLEYEBÝLÝRSÝNÝZ!
       AND NOT EXISTS(SELECT * FROM STOKIZLEME SI WHERE F.FATBASID = SI.BASLIKID AND F.ID = SI.SATIRID) -- STOKIZLEMEDE OLMAYAN
       AND FB.TUR <> 2 -- TÜRÜ DEVÝR DIÞINDAKÝ
       AND FB.FATURATARIH >= '2020-01-01 00:00' -- X TARÝHÝNDEN SONRA
       AND FB.DURUM <> 6 -- BELGE DURUMU ÝPTAL DIÞINDAKÝ
                   AND FB.TIPI NOT IN (2,3) -- ÝADE VE FÝYAT FARKI DIÞINDAKÝ
ORDER BY 2
--ANADEPO ÝRSALÝYE VE FATURA(14,15) DA ÝZLEM GÖZÜKMÜYOR AMA LOT VARSA BUNU ÇALIÞTIR YUKARIDAKÝ SORGUDA 119 KONSÝNYE DIÞINDAKÝ ÝÇÝN YAPILABILIR ÇÖZÜM 

INSERT INTO STOKIZLEME(STOKID,BELGETUR,BASLIKID,SATIRID,IZLEMTUR,KALAN,YER,YERID,EKLEYEN,EKLEMETARIHI,DONUSID,ADET,SERILOTID)VALUES(6444,14,127115,1677505,5,0,0,0,2,GETDATE(),0,0,13247)


INSERT INTO STOKIZLEMEDEPO (IZLEMID,DEPOID,ADET)VALUES
('irsaliye insert çalýþtýktan sonra ona gelen ýd buraya gelecek',1,'-1')

INSERT INTO STOKIZLEME(STOKID,BELGETUR,BASLIKID,SATIRID,IZLEMTUR,KALAN,YER,YERID,EKLEYEN,EKLEMETARIHI,DONUSID,ADET,SERILOTID)VALUES(6444,15,127117,1677515,5,1,0,0,2,GETDATE() ,'irsaliye insert çalýþtýktan sonra ona gelen ýd buraya gelecek',1,13247)
INSERT INTO STOKIZLEMEDEPO (IZLEMID,DEPOID,ADET)VALUES
('USTEKÝ ÝNSERT ÇALISTIKTAN SONRAKÝ OLUÞAN ID', 1	,0)
--ID atan sorgu

SELECT 
       *,
       DONUSEN = (SELECT SUM(ADET) FROM STOKIZLEME SS WHERE SS.STOKID = SI.STOKID AND SS.SERILOTID = SI.SERILOTID AND SS.DONUSID = SI.ID),
       KALAN = SI.ADET - ISNULL((SELECT SUM(ADET) FROM STOKIZLEME SS WHERE SS.STOKID = SI.STOKID AND SS.SERILOTID = SI.SERILOTID AND SS.DONUSID = SI.ID),0),
       SORGU = 'UPDATE STOKIZLEME SET KALAN = ' + CONVERT(VARCHAR(10),(SI.ADET - ISNULL((SELECT SUM(ADET) FROM STOKIZLEME SS WHERE SS.STOKID = SI.STOKID AND SS.SERILOTID = SI.SERILOTID AND SS.DONUSID = SI.ID),0))) + ' WHERE ID = ' + CONVERT(VARCHAR(10),SI.ID)
FROM 
       STOKIZLEME SI WHERE BELGETUR = 119
       AND
       KALAN <> (   SI.ADET - ISNULL((SELECT SUM(ADET) FROM STOKIZLEME SS WHERE SS.STOKID = SI.STOKID AND SS.SERILOTID = SI.SERILOTID AND SS.DONUSID = SI.ID),0))


	   SELECT*FROM STOKLAR WHERE ID=6444
--Aþaðýdaki sorgu ile ilgili kod u yazýp stok kaleminin konsinye belge kalan toplamýný görebilirsiniz.

SELECT 
       SUM(SI.KALAN) AS TOPLAM_KALAN
FROM 
       STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
WHERE
       S.KOD = '100-10351-012'
       AND SI.BELGETUR = 119

---- SKT-LOT Takibi (Konsinye) raporundaki lot toplamlarý ile STOKDURUMIZLEME tablosundaki lot kalan farklarýný listelemektedir.
SELECT
       ID,
       LOTID,
       LOT,
       RAPOR_KALAN = SUM(X.KALAN),
       STOK_DURUM_KALAN = SDI.KALAN
FROM ( 
       SELECT
             S1.ID,
             LOTID = SL.ID,
             LOT=isnull(SL.LOTNO,''),
             KALAN = CASE WHEN FB1.GIRISDEPO = 9 AND FB1.TUR <> 14 THEN 1*(SE1.ADET)
                              WHEN FB1.CIKISDEPO = 9 AND FB1.TUR <> 14 THEN -1*(SE1.ADET)
                              WHEN FB1.CIKISDEPO = 9 AND FB1.TUR = 14 AND NOT EXISTS(SELECT * FROM STOKIZLEME SI WHERE SI.DONUSID = SE1.ID) THEN -1*(SE1.ADET)
                              ELSE SE1.KALAN 
                           END
       FROM 
             STOKIZLEME SE1 INNER JOIN FATURA F1 on SE1.SATIRID=F1.ID 
                                     INNER JOIN FATBASLIK FB1 on F1.FATBASID=FB1.ID AND SE1.BASLIKID=FB1.ID 
                                     INNER JOIN STOKLAR S1 on S1.ID=F1.URUNID
                                     INNER JOIN STOKSERILOT SL ON SL.ID=SE1.SERILOTID
       WHERE 
             S1.KOD = '100-10351-012'
             AND FB1.DURUM<>6
             AND (GIRISDEPO = 9 OR CIKISDEPO = 9)
             AND NOT EXISTS(SELECT * FROM STOKIZLEME SI WHERE SI.DONUSID = SE1.ID AND SE1.BELGETUR = 14)
) AS X LEFT JOIN STOKDURUMIZLEME SDI ON SDI.STOKID = X.ID AND SDI.DEPOID = 9 AND SDI.SERILOTID = X.LOTID
GROUP BY 
       ID,
       LOTID,
       LOT,
       SDI.KALAN
HAVING
       SUM(X.KALAN) <> SDI.KALAN

-- STOKIZLEME tablosundaki ilgili stok kodu ve lot numarasýna göre belge türlerine göre toplam adetler listelenir.
SELECT 
       SI.BELGETUR,
       SUM(ADET)
FROM 
       STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
                             INNER JOIN STOKSERILOT SL ON SL.ID = SI.SERILOTID AND SL.STOKID = SI.STOKID
WHERE
       S.KOD = '100-10351-012'
       AND LOTNO = '211346'
GROUP BY
       SI.BELGETUR

-- ÇIKIÞ DEPOSU ANADEPO OLUP KAYNAÐI KONSÝNYE OLAN FATURA ID LERI

SELECT 
       DISTINCT FB.ID
FROM 
       FATURA F INNER JOIN FATBASLIK FB ON FB.ID = F.FATBASID
WHERE
       FB.CIKISDEPO = 1
       AND F.YERI = 462

--STOKIZLEME tablosu ile stok izlem (STOKDURUMIZLEME) arasýnda fark olduðunda hangi lotta problem olduðuna bakýlmalýdýr. Bunun için aþaðýdaki sorgu ile karþýlaþtýrabilirsiniz.

SELECT 
       LOTNO,
       SUM(SI.KALAN) AS SI_KALAN,
       SDI.KALAN AS SDI_KALAN
FROM
       STOKIZLEME SI INNER JOIN STOKSERILOT SL ON SL.STOKID = SI.STOKID AND SL.ID = SI.SERILOTID 
                     INNER JOIN STOKLAR S ON S.ID = SI.STOKID
                                  LEFT JOIN STOKDURUMIZLEME SDI ON SDI.STOKID = SI.STOKID AND SDI.SERILOTID = SI.SERILOTID AND SDI.DEPOID = 9
WHERE 
       S.KOD = '100-10351-012
' 
          AND SI.BELGETUR = 119 
GROUP BY 
       SL.LOTNO,
       SDI.KALAN
HAVING 
       SUM(SI.KALAN) <> SDI.KALAN


--CIKIS DEPOSU KONSINYE OLAN SATIS FATURASI ADET
SELECT 
       SI.BELGETUR,
       SUM(ADET) AS ADET
FROM 
       STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
                             INNER JOIN STOKSERILOT SL ON SL.ID = SI.SERILOTID AND SL.STOKID = SI.STOKID
WHERE
       S.KOD = '100-10351-012'
       AND LOTNO = '211346'
       AND SI.BELGETUR = 15
       AND EXISTS(SELECT * FROM STOKIZLEME SS WHERE SS.ID = SI.DONUSID AND SS.BELGETUR = 119)
GROUP BY
       SI.BELGETUR

--CIKIS DEPOSU KONSINYE OLUP KAYNAÐI KONSINYE OLMAYAN SATIÞ FATURALARI
SELECT 
       S.KOD,
       FB.*
FROM 
       STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
                             INNER JOIN STOKSERILOT SL ON SL.ID = SI.SERILOTID AND SL.STOKID = SI.STOKID
                             INNER JOIN FATBASLIK FB ON FB.ID = SI.BASLIKID AND FB.TUR = SI.BELGETUR
WHERE
       SI.BELGETUR = 15
       AND NOT EXISTS(SELECT * FROM STOKIZLEME SS WHERE SS.ID = SI.DONUSID AND SS.BELGETUR = 119)
       AND FB.CIKISDEPO = 9

--Belgenin deposu Konsinye çýkýþ deposu olup dönüþen id si stok izlemede olmayan kayýtlar (Belge kaynaðý yok ya da eksik kayýtlar)
--Sorgu 1

SELECT 
       S.KOD,
       SI.* 
FROM 
       STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
                             INNER JOIN FATBASLIK FB ON FB.ID = SI.BASLIKID AND FB.TUR = SI.BELGETUR
WHERE
       ISNULL(SI.DONUSID,0) <> 0
       AND NOT EXISTS(SELECT * FROM STOKIZLEME SS WHERE SS.ID = SI.DONUSID)
       AND FB.CIKISDEPO = 9
       AND FB.TUR IN (14,15)   

--IZLEMI OLMAYAN KAYIT KONTROL SORGUSU
SELECT 
	F.IZLEME,SI.ID,FB.FATURATARIH,FB.TUR,SI.IZLEMTUR,F.IZLEME,S.IZLEME,*
FROM
	FATURA F INNER JOIN STOKLAR S ON S.ID = F.URUNID
			 INNER JOIN FATBASLIK FB ON FB.ID = F.FATBASID
			 LEFT JOIN STOKIZLEME SI ON SI.BASLIKID = FB.ID AND SI.SATIRID = F.ID AND SI.BELGETUR = FB.TUR AND SI.STOKID = F.URUNID
			 LEFT JOIN STOKSERILOT SL ON SL.ID = SI.SERILOTID AND SL.STOKID = SI.STOKID
WHERE
	S.KOD = '100-10351-040'
	AND ISNULL(SI.ID,'') = ''
	AND FB.TUR <> 2
	AND FB.DURUM <> 6

--STOKLARDAKÝ FARKLARI BULMA

SELECT
S.ID,
       S.KOD,
       S.STOKADI,
       D.DEPOADI,
       SD.KALAN AS SD_KALAN,
       SDI.SDI_KALAN
FROM
       STOKDURUM SD 
             INNER JOIN (SELECT STOKID, DEPOID, SUM(KALAN) AS SDI_KALAN FROM STOKDURUMIZLEME GROUP BY STOKID, DEPOID) SDI ON SDI.STOKID = SD.STOKID 
             AND SDI.DEPOID = SD.DEPOID
             INNER JOIN STOKLAR S ON S.ID = SD.STOKID
             INNER JOIN DEPOLAR D ON D.ID = SD.DEPOID
WHERE
       SD.KALAN <> SDI.SDI_KALAN
         AND S.DURUM <>0

--STOKIZLEMEDE OLUP FATURA TABLOSUNDA KAYDI OLMAYAN KAYITLAR, STOKIZLEMEDEN SÝLÝNMELÝDÝR.
SELECT 
	SORGU = 'DELETE FROM STOKIZLEME WHERE ID = ' + CONVERT(VARCHAR(10),SI.ID),
	S.KOD,
	SI.* 
FROM 
	STOKIZLEME SI INNER JOIN STOKLAR S ON S.ID = SI.STOKID
WHERE
	NOT EXISTS(SELECT * FROM FATURA F WHERE F.FATBASID = SI.BASLIKID AND F.ID = SI.SATIRID AND F.URUNID = SI.STOKID)
	
--
SELECT 
	* 
FROM 
	STOKIZLEME SI
WHERE 
	SI.STOKID = 6444 
	AND SI.SERILOTID = 10049
	AND NOT EXISTS(SELECT * FROM STOKIZLEME SS WHERE SS.DONUSID = SI.ID)
	AND BELGETUR = 119 AND KALAN > 0
ORDER BY 
	ID 
DESC

UPDATE SI SET SI.SERILOTID = 13247 FROM STOKIZLEME SI WHERE ID --IN (399494,410316,410216,409856,408471,408204,407483,407175,406911,406100,406053)

--MÝKTARSAL KARÞILAÞTIRMA
SELECT 
	S.KOD,
	S.STOKADI,
	F.FATBASID,
	F.ID,
	ABS(F.ADET),
	SUM(SI.ADET) AS SI_ADET
FROM 
	STOKIZLEME SI INNER JOIN FATURA F ON F.ID = SI.SATIRID AND F.FATBASID = SI.BASLIKID AND F.URUNID = SI.STOKID
				  INNER JOIN STOKLAR S ON S.ID = SI.STOKID
GROUP BY
	S.KOD,
	S.STOKADI,
	F.FATBASID,
	F.ID,
	F.ADET
HAVING
	ABS(F.ADET) <> SUM(SI.ADET)

	-- stokýzleme ile stokýzleme adet

SELECT SS.*,S.KOD, S.URUNNO, S.STOKADI FROM
(
SELECT SD.STOKID, KALAN1=SUM(SD.KALAN),
IZLEM=ISNULL((SELECT SUM(SDI.KALAN) FROM STOKDURUMIZLEME SDI WHERE SD.STOKID = SDI.STOKID),0)
FROM STOKDURUM SD 
GROUP BY STOKID

) AS SS
INNER JOIN STOKLAR S ON S.ID=SS.STOKID
WHERE KALAN1 <> IZLEM AND S.DURUM=1  AND S.IZLEME = 5


--ILGILI STOK KALEMININ KONSINYE BELGEDEKI ADET ILE STOKIZLEMEDEPODAKI ADETI FARKLI OLAN KAYITLARIN LISTESI * STOKIZLEME VE STOKIZLEMEDEPO ADET AYNI OLMALIDIR!
SELECT
	*
FROM 
	STOKIZLEME SI INNER JOIN STOKSERILOT SL ON SL.ID = SI.SERILOTID AND SI.STOKID = SL.STOKID 
				  INNER JOIN STOKIZLEMEDEPO SD ON SD.IZLEMID = SI.ID
WHERE 
	SI.STOKID = 6741 AND BELGETUR = 119
	AND SI.ADET <> ABS(SD.ADET)
